---
# Handlers
- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Update CA certificates
  ansible.builtin.command: update-ca-certificates
  changed_when: true