---
- name: Configure pending packages
  command: dpkg --configure -a
  become: true
  register: configure_packages_result
- debug:
    msg: "Pending packages configured: {{ configure_packages_result.changed }}"

- name: Clean up the package database
  apt:
    autoclean: yes
  become: true
  register: cleanup_packages_result
- debug:
    msg: "Package database cleaned: {{ cleanup_packages_result.changed }}"

- name: Remove unnecessary packages
  apt:
    autoremove: yes
    purge: yes
  become: true
  register: remove_packages_result
- debug:
    msg: "Unnecessary packages removed: {{ remove_packages_result.changed }}"

- name: Force upgrade of specific deferred packages
  apt:
    name:
      - grub-common
      - grub-efi-amd64-bin
      - grub-efi-amd64-signed
      - grub-pc
      - grub-pc-bin
      - grub2-common
    state: latest
    force: yes
  become: true
  register: force_upgrade_packages_result
- debug:
    msg: "Specific packages upgraded: {{ force_upgrade_packages_result.changed }}"

- name: Check for updates
  apt:
    update_cache: yes
  become: true
  register: check_updates_result
- debug:
    msg: "Package cache updated: {{ check_updates_result.changed }}"

- name: Perform system upgrade
  apt:
    upgrade: dist
  become: true
  register: upgrade_result
  notify: system_reboot
- debug:
    msg: "System upgrade performed: {{ upgrade_result.changed }}"

- debug:
    msg: "System reboot notified due to upgrades"
  when: upgrade_result.changed