---
vm_ip: "192.168.1.27"  # Replace with your VM's IP
acme_validation_method: "local"
cert_dir: "/etc/ssl/mycerts"
acme_sh_email: "mulendaraphael@yahoo.fr"
docker_certs_dir: "/etc/docker/certs.d/{{ vm_ip }}"