- name: Reload shell
  ansible.builtin.shell: |
    source /root/.bashrc
  args:
    executable: /bin/bash

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Update CA certificates
  ansible.builtin.command: update-ca-certificates
  changed_when: true