- name: Ensure SSL directory exists
  file:
    path: /etc/harbor/ssl
    state: directory
    mode: '0755'
  become: yes

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: /etc/harbor/ssl/key.pem
  become: yes

- name: Generate self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/harbor/ssl/cert.pem
    privatekey_path: /etc/harbor/ssl/key.pem
    provider: selfsigned
    selfsigned_create_subject_key_identifier: create_if_not_provided
    selfsigned_not_before: "{{ ansible_date_time.iso8601 }}"
    selfsigned_not_after: "+365d"
  become: yes

- name: Set permissions for private key
  file:
    path: /etc/harbor/ssl/key.pem
    mode: '0600'
  become: yes

- name: Set permissions for certificate
  file:
    path: /etc/harbor/ssl/cert.pem
    mode: '0644'
  become: yes