---
- name: Remove apt lock files if they exist
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/apt/lists/lock
    - /var/cache/apt/archives/lock
  register: remove_lock_files
- debug:
    var: remove_lock_files

- name: Update system packages
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == 'Debian'
  register: update_packages
- debug:
    var: update_packages

- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
  register: install_java
- debug:
    var: install_java

- name: Add Jenkins repository key (ASCII-armored format)
  get_url:
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
    dest: /etc/apt/trusted.gpg.d/jenkins.asc
    mode: '0644'
  register: add_jenkins_key
- debug:
    var: add_jenkins_key

- name: Convert Jenkins GPG key to binary format
  command: >
    gpg --dearmor -o /etc/apt/trusted.gpg.d/jenkins.gpg /etc/apt/trusted.gpg.d/jenkins.asc
  args:
    creates: /etc/apt/trusted.gpg.d/jenkins.gpg
  register: convert_gpg_key
- debug:
    var: convert_gpg_key

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/jenkins.gpg] https://pkg.jenkins.io/debian-stable binary/'
    state: present
    filename: 'jenkins'
  register: add_jenkins_repo
- debug:
    var: add_jenkins_repo

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  register: install_jenkins
- debug:
    var: install_jenkins

- name: Ensure Jenkins is started and enabled
  systemd:
    name: jenkins
    state: started
    enabled: yes
  register: start_jenkins
- debug:
    var: start_jenkins

- name: Wait for Jenkins to start
  uri:
    url: http://localhost:8080
    status_code: 200
    timeout: 300
  register: jenkins_status
  until: jenkins_status.status == 200
  retries: 10
  delay: 30
- debug:
    var: jenkins_status

- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - docker
    - ansible
    - pipeline
    - credentials
    - ssh-slaves
  register: install_plugins
- debug:
    var: install_plugins