version: '3.8'

services:
  cicd-test-app:
    image: 192.168.1.27:8080/cicd-infra/cicd-test-app:16  # Use harbor_registry, app_name, and image_tag
    container_name: cicd-test-app
    restart: always
    ports:
      - "8080:80"
    environment:
      - ENV=production
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=password
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
