---
- name: Install Harbor
  shell: |
    wget -O harbor-offline-installer-v2.4.1.tgz https://github.com/goharbor/harbor/releases/download/v2.4.1/harbor-offline-installer-v2.4.1.tgz
    tar -xvf harbor-offline-installer-v2.4.1.tgz
    cd harbor
    ./install.sh
  args:
    creates: /data/harbor/
  register: install_harbor_result
- debug:
    msg: "Harbor installation attempted: {{ install_harbor_result.changed }}, Return code: {{ install_harbor_result.rc }}"
- debug:
    var: install_harbor_result.stdout_lines
  when: install_harbor_result.changed