- name: Provision CI/CD infrastructure
  hosts:
    - jenkins
    - docker
  gather_facts: yes
  become: true
  vars:
    harbor_https_enabled: false  # Ensure this variable is defined
  pre_tasks:
    - name: Ensure servers are reachable
      ping:

  tasks:
    - name: Include Jenkins role
      include_role:
        name: jenkins
      when: inventory_hostname in groups['jenkins']
      tags: jenkins

    - name: Include Ansible role
      include_role:
        name: ansible
      when: inventory_hostname in groups['jenkins']
      tags: ansible

    - name: Include Docker role
      include_role:
        name: docker
      when: inventory_hostname in groups['docker']
      tags: docker

    # - name: Generate self-signed certificate for Harbor
    #   include_role:
    #     name: harbor_certificate
    #   when: inventory_hostname in groups['docker']
    #   tags: harbor-certificate

    - name: Include Harbor role
      include_role:
        name: harbor
      when: inventory_hostname in groups['docker']
      tags: harbor
