- name: Provision CI/CD GitHub Actions Runner
  hosts:
    - 'git-runners'
  gather_facts: yes
  become: true
  pre_tasks:
    - name: Ensure servers are reachable
      ping:

  tasks:
    - name: Setup GitHub Actions Runner
      include_role:
        name: github_runner
      tags: github_runner